version: '4.1'
services:
  db:
    container_name: db
    image: postgres:10.4
    ports:
      - "2222:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: qorakoli_db
      POSTGRES_DB: qorakoli_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  postgrs_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/qorakoli_db
      DATABASE_USER: qorakoli_db
      DATABASE_PASSWORD: 12345
    ports:
      - "8080:8080"

